// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

#nullable disable

namespace HotelSystem.ReservationEntities
{
    public partial class Reservation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDay { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int NumberGuest { get; set; }
        public string StreetAddress { get; set; }
        public string AptSuite { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        string type;
        public string RoomType { get { return type.Trim(); } set => type = value; }
        string floor;
        public string RoomFloor { get { return floor.Trim(); } set => floor = value; }
        string number;
        public string RoomNumber { get { return number.Trim(); } set => number = value; }
        double tBill;
        public double TotalBill { 
            get 
            {
                int total = 0;
                if (RoomType.Equals("Single"))
                {
                    total = 149;
                }
                else if (RoomType.Equals("Double"))
                {
                    total = 299;
                }
                else if (RoomType.Equals("Twin"))
                {
                    total = 349;
                }
                else if (RoomType.Equals("Duplex"))
                {
                    total = 399;
                }
                else if (RoomType.Equals("Suite"))
                {
                    total = 499;
                }

                if (NumberGuest >= 3)
                {
                    total += (NumberGuest * 5);
                }
                return total;
            }
            
            set {
                if (RoomType.Equals("Single"))
                {
                    tBill = 149;
                }
                else if (RoomType.Equals("Double"))
                {
                    tBill = 299;
                }
                else if (RoomType.Equals("Twin"))
                {
                    tBill = 349;
                }
                else if (RoomType.Equals("Duplex"))
                {
                    tBill = 399;
                }
                else if (RoomType.Equals("Suite"))
                {
                    tBill = 499;
                }
            }    
        }
        string Ptype;
        public string PaymentType { get { return Ptype.Trim(); } set=> Ptype = value; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardExp { get; set; }
        public string CardCvc { get; set; }
        public DateTime ArrivalTime { get; set; }
        public DateTime LeavingTime { get; set; }
        public bool CheckIn { get; set; }
        public int BreakFast { get; set; }
        public int Lunch { get; set; }
        public int Dinner { get; set; }
        public bool Cleaning { get; set; }
        public bool Towel { get; set; }
        public bool SSurprise { get; set; }
        public bool SupplyStatus { get; set; }
        int fBill;
        public int FoodBill {
            get => (BreakFast * 7) + (Lunch * 15) + (Dinner * 15);
            set => fBill = (BreakFast * 7) + (Lunch * 15) + (Dinner * 15);
        }
        public override string ToString()
        {
            return $"{Id} | {FirstName} {LastName} | {PhoneNumber}";
        }

        public string ReservedRoomToString()
        {
            return $"{RoomNumber.Trim()} | {RoomType.Trim()} | {Id} | {FirstName} {LastName} | {PhoneNumber} | {ArrivalTime} | {LeavingTime} ";
        }

        public string OccupiedRoomToString()
        {
            return $"{RoomNumber.Trim()} | {RoomType.Trim()} | {Id} | {FirstName} {LastName} | {PhoneNumber} ";
        }

        string day;

        public string DAY
        {
            get
            {
                string[] arr = BirthDay.Split("-");
                return arr[1];
            }
        }
        public string MONTH
        {
            get
            {
                string[] arr = BirthDay.Split("-");
                return DateTime.ParseExact(arr[0].Trim(), "MMMM", CultureInfo.CurrentCulture).Month.ToString();
            }
        }
        public string YEAR
        {
            get
            {
                string[] arr = BirthDay.Split("-");
                return arr[2];
            }
        }
        public string CARDEXPMONTH
        {
            get
            {
                string r = "";
                string[] arr = CardExp.Split("/");
                r = arr[0];
                return r;
            }
        }
        public string CARDEXPYEAR
        {
            get
            {
                string r = "";
                string[] arr = CardExp.Split("/");
                r = arr[1];
                return r;
            }
        }
    }
}