// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HotelSystem.LoginEntities
{
    public partial class Kitchen
    {
        string name;
        public string UserName { get => name; set => name = value; }
        string pass;
        public string PassWord { get => pass; set => pass = value; }
    }
}